### ISSUE TITLE
[Redshift] Update certain columns values

### ISSUE THREAD

**Issue by Olaktal** [embulk/embulk-output-jdbc#139]
Hello,

I need to update the value of multiple columns in a table and I'm not sure I can do it for now so maybe I'm asking for a possible evolution. Here is an example of what I need:

```
create table questions ( question_id int IDENTITY(1,1), title varchar(100),content varchar(1000),average_answer_time int)

insert into questions (title,content) VALUES ('title1', 'content1'),('title2', 'content2'),('title3', 'content3')
```

I have to add data to the table rows but I can't do it during the first import for multiple factors (not available at that time, in another database or format, ...). So I need to update multiple rows afterwards.
Here is a simple example of input data:

![image](https://cloud.githubusercontent.com/assets/5711131/19483276/1992ffc8-9554-11e6-8fe4-f99c7a8b1cc8.png)

Basically, the out part of the YML file would be like that:

```
out:
  type: redshift
  host: ***
  user: ***
  password: ***
  database: ***
  schema: ***
  table: questions
  access_key_id: ***
  secret_access_key: ***
  iam_user_name: ***
  s3_bucket: ***
  s3_key_prefix: ***
  mode: update
  update_keys: ["question_id "] (Could have multiple update_keys)
  column_updated: 
    average_answer_time : {value_type: int}
   where:  (not used here but it can be usefull, I already have use cases in my head)
```

Is it possible @hito4t  ?
I suppose this plugin will be considered as the most evolved plugin in embulk with this functionality ahah

Best regards,
Vincent
