### ISSUE TITLE
Merge imports in single session

### ISSUE THREAD

**Issue by kakoni** [embulk/embulk-output-jdbc#156]
I'll have a CSV like this;
```csv
1,2,3
1,5,6
````
output table (in postgresql)
```sql
create table embulk_test(id integer, a text, b text);
alter table embulk_test add primary key(id);
```

If I import this with simple config
```
in:
  type: file
  path_prefix: file.csv
  parser:
    type: csv
    columns:
      - {name: id, type: string}
      - {name: a, type: string}
      - {name: b, type: string}
out:
  type: postgresql
  table: embulk_test
  options: {loglevel: 2}
  mode: merge
```
I'll have 1,2,3 in the table. Would it be possible to do merge insert?
