### ISSUE TITLE
[Oracle][General questions] Can i load data oracle on NOLOGGING ?

### ISSUE THREAD

**Issue by morihaya** [embulk/embulk-output-jdbc#257]
Hi there.
I was very happy to replaced the sqlloader with digdag and embulk.
However, one problem is that the amount of output from Archive Log has increased significantly.
Is it possible to load data as NOLOGGING mode with embulk-output-oracle plugin?

My embulk yml.liquied is here.

```yaml
out:
  type: oracle
  driver_path: {{ env.oracle_driver }}
  url: jdbc:oracle:thin:@//{{ env.oracle_dest_host }}/{{ env.oracle_dest_sid }}
  user: {{ env.oracle_dest_user }}
  password: {{ env.oracle_dest_pass }}
  schema: {{ env.oracle_dest_schema }}
  table: {{ env.table }}
  mode: truncate_insert
  insert_method: direct
```
