### ISSUE TITLE
embulk-output-sqlserver can't connect to db with instance name

### ISSUE THREAD

**Issue by hieudion** [embulk/embulk-output-jdbc#262]
I faced this issue when using the new version of mssql:JDBC 7.2.2.
It runs fine with `jtds:jdbc` but when updates to `mssql:jdbc` i can't connect to the db. DB is on Azure I think.
Just raise the issue here so we can aware of it.

**Comment by nickolay** [comment]
FWIW, specifying an instance name works fine here (not Azure, but a local SQL Server 2012):
```
  out:
    type: sqlserver
  #  driver_path: %(embulk_path)s\mssqljdbc\mssql-jdbc-7.2.1.jre8.jar
    driver_path: %(embulk_path)s\mssqljdbc\mssql-jdbc-7.4.1.jre8.jar
    
    host: ...
    instance: ...
    user: ...
    password: ...
    mode: insert_direct
    insert_method: native
  # ...
```
