### ISSUE TITLE
Failed to output chinese emoji to mysql

### ISSUE THREAD

**Issue by YunLongND** [embulk/embulk-output-jdbc#306]
My mysql uses code utf8mb4, and mysq's temporary table code is utf8mb4, 
When I insert data into mysql temporary table, it has the following error:
`org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.sql.BatchUpdateException: Incorrect string value: '\xF0\x9F\xA4\xA3' for column ......`

Can someone help me solve this problem? thanks.

**Comment by hiroyuki-sato** [comment]
Hello, @YunLongND 

* MySQL: 8.0.28
* embulk: 0.9.24
* embulk-output-mysql: 0.10.2

I could insert the following emoji into the MySQL database without any special configuration.
(I created the table using `mysql` command)

Could you tell me more detail about your environment (configuration, database version, and so on)?

```sql
CREATE TABLE `example` (
  `id` bigint DEFAULT NULL,
  `account` bigint DEFAULT NULL,
  `time` timestamp NULL DEFAULT NULL,
  `purchase` timestamp NULL DEFAULT NULL,
  `comment` text COLLATE utf8mb4_general_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
```

```csv
id,account,time,purchase,comment
1,32864,2015-01-27 19:23:49,20150127,embulk
2,14824,2015-01-27 19:01:23,20150127,embulk jruby
3,27559,2015-01-28 02:20:02,20150128,"Embulk ""csv"" parser plugin"
4,11270,2015-01-29 11:54:36,20150129,🍺🍻🍣
```


```
in:
  type: file
  path_prefix: sample_
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out:
  type: mysql
  host: localhost
  mode: insert
  user: user
  password: password
  database: embulk_test
  table: example
```

**Comment by YunLongND** [comment]
@hiroyuki-sato Thank you very much for your attention to my question.
My configuration information is as follows:
- mysql version: 5.7.35
- embulk: 0.9.23
- embulk-output-mysql: 0.10.2
`in:
  type: redshift
  host: redshift_host
  user: redshift_user
  password: redshift_password
  database: redshift_database
  port: 5439
  fetch_rows: 1000
  query: select * from schema.table
  options: {useUnicode: true, characterEncoding: utf8}
out:
  type: mysql
  host: mysql_host
  port: 3306
  user: mysql_user
  password: mysql_password
  database: mysql_database
  schema: mysql_schema
  table: mysql_table
  create_table_option: DEFAULT CHARSET=utf8mb4
  options: {loglevel: 2, useUnicode: true, characterEncoding: utf8}
  mode: truncate_insert
  node_count: 16`

I noticed that when I use mode truncate_insert to transfer data from Redshift to MySQL, embed first creates a temporary table in mysql, then stores the data in the temporary table, and then transfers the data in the temporary table to the target table. 
My chinese emoji have been successfully stored in redshift, and the temporary table has been successfully created, and the code of the temporary table is utf8mb4.
However, when I insert the emoji data in redshift into the temporary table of MySQL, the above error occurs.
If you need more information, please let me know.

**Comment by YunLongND** [comment]
@hiroyuki-sato Thank you very much for your attention to my question.
My configuration information is as follows:
- mysql version: 5.7.35
- embulk: 0.9.23
- embulk-output-mysql: 0.10.2
`in:
  type: redshift
  host: redshift_host
  user: redshift_user
  password: redshift_password
  database: redshift_database
  port: 5439
  fetch_rows: 1000
  query: select * from schema.table
  options: {useUnicode: true, characterEncoding: utf8}
out:
  type: mysql
  host: mysql_host
  port: 3306
  user: mysql_user
  password: mysql_password
  database: mysql_database
  schema: mysql_schema
  table: mysql_table
  create_table_option: DEFAULT CHARSET=utf8mb4
  options: {loglevel: 2, useUnicode: true, characterEncoding: utf8}
  mode: truncate_insert
  node_count: 16`

I noticed that when I use mode truncate_insert to transfer data from Redshift to MySQL, embed first creates a temporary table in mysql, then stores the data in the temporary table, and then transfers the data in the temporary table to the target table. 
My chinese emoji have been successfully stored in redshift, and the temporary table has been successfully created, and the code of the temporary table is utf8mb4.
However, when I insert the emoji data in redshift into the temporary table of MySQL, the above error occurs.
If you need more information, please let me know.

**Comment by hiroyuki-sato** [comment]
Hello, @YunLongND 

* Did you try to insert data into the `mysql_table` using `mysql` command? (ex. 1insert into mysql_table values(1,"🍻🍣🍺") ;`
* Did you try to insert data into another table with `mode: insert`?

I got the same error message if the target table does not support `utf8mb4`.
In my case, I altered changed the database character set and recreate the table.
After that, I succeed insert data.

`truncate_insert` does not recreate the target table.
Did you check the table schema using `show create table mysql_table`?

I inserted the same data using `mode: truncate_insert`.

**Comment by YunLongND** [comment]
@hiroyuki-sato 
I have checked that both my temporary table and my target table are coded utf8mb4. 
And using SQL directly to insert emoji into the table can be successful. 
Based on the above communication, we cannot confirm where the problem is, so if there is no better suggestion on this issue, let's leave it here for now.
I found a little bit of a similar problem in other embulk projects, I don't know if it's related.
https://github.com/embulk/embulk-input-s3/issues/75
Thank you again for your efforts.

**Comment by hiroyuki-sato** [comment]
Hello, @YunLongND 

I succeed insert emoji in the following environment and configuration.

* embulk 0.9.24
* embulk-output-mysql: 0.10.2
* MySQL: 5.7.38

```
[mysqld]
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci

[client]
default-character-set=utf8mb4
```

```csv
id,comment
2,embulk jruby
4,🍺🍻🍣
```

```yaml
in:
  type: file
  path_prefix: sample_2
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: comment, type: string}
out:
  type: mysql
  host: 127.0.0.1
  mode: truncate_insert
  user: user
  password: password
  database: embulk_test
  table: example
```

docker-compose.yml

```
   version: '3'

   services:
     db:
       image: mysql:5.7
       container_name: mysql_container
       environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: embulk_test
         MYSQL_USER: user
         MYSQL_PASSWORD: password
       volumes:
       - ./docker/db/data:/var/lib/mysql
       - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
       restart: always
       ports:
       - 3306:3306
```
