### ISSUE TITLE
postgresql driver does not work properly leglevel without quote.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk-output-jdbc#43]
postgresql driver does not work properly `leglevel` without quote.

in [README](https://github.com/embulk/embulk-output-jdbc/blob/master/embulk-output-postgresql/README.md) example.

```yaml
out:
  type: postgresql
  # ...
  options: {loglevel: 2}
```

I got the following error.

```
Error: org.postgresql.util.PSQLException: Properties for the driver contains a non-string value for the key loglevel
```

With quote, work fine.

```yaml
out:
  type: postgresql
  # ...
  options: {loglevel: "2"}
```

Should I update document?
