### ISSUE TITLE
Support Oracle database service name

### ISSUE THREAD

**Issue by hito4t** [embulk/embulk-output-jdbc#95]
Now `database` means SID.
For using database service name, must set full JDBC URL, but it is inconvenient.

**Comment by pengfeiz** [comment]
> For using database service name, must set full JDBC URL, but it is inconvenient.

if I do use service name, where to set full JDBC URL, in 

``` yaml
in: 
    type: oracle
    driver_path:......
    database: here??
out: 
```

**Comment by pengfeiz** [comment]
For using database service name, use `url` instead of host/database 

```yaml
in:
    type: oracle
    driver_path:.......ojdbc6.jar
    url: jdbc:oracle:thin:@x.x.x.x/<service_name>
out:
    type: stdout
```
But what happened if there are multiple port or host in `tnsname.ora` file
```
(ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = x.x.x.x)(PORT = 1524))
      (ADDRESS = (PROTOCOL = TCP)(HOST = x.x.x.x)(PORT = 1525))
      (LOAD_BALANCE = ON)
      (FAILOVER = ON)
    )
```
